import {
  chmodSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync,
} from "node:fs";
import { execFileSync, spawnSync } from "node:child_process";
import type { SpawnSyncReturns } from "node:child_process";
import { tmpdir } from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { afterEach, describe, expect, it } from "vitest";

const script = path.resolve("scripts/dev-session.ts");
const tsxImport = createRequire(import.meta.url).resolve("tsx");
const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

function fixture(): { root: string; repo: string; worktrees: string; bin: string } {
  const root = mkdtempSync(path.join(tmpdir(), "scm-dev-session-"));
  roots.push(root);
  const repo = path.join(root, "repo");
  const worktrees = path.join(root, "worktrees");
  const bin = path.join(root, "bin");
  mkdirSync(repo);
  mkdirSync(bin);
  writeFileSync(path.join(repo, ".gitignore"), ".env\n.data/\n");
  writeFileSync(path.join(repo, "tracked.txt"), "initial\n");
  execFileSync("/usr/bin/git", ["init", "-q"], { cwd: repo });
  execFileSync("/usr/bin/git", ["add", ".gitignore", "tracked.txt"], { cwd: repo });
  execFileSync(
    "/usr/bin/git",
    ["-c", "user.name=Test", "-c", "user.email=test@example.com", "commit", "-qm", "initial"],
    { cwd: repo },
  );
  writeFileSync(
    path.join(repo, ".env"),
    "AUTH_SECRET=main-secret-must-not-copy\nFEISHU_APP_SECRET=main-feishu-secret\n",
  );
  return { root, repo, worktrees, bin };
}

function run(
  fx: ReturnType<typeof fixture>,
  args: string[],
  extraEnv: Record<string, string | undefined> = {},
): SpawnSyncReturns<string> {
  return spawnSync(process.execPath, ["--import", tsxImport, script, ...args], {
    cwd: fx.repo,
    encoding: "utf8",
    env: {
      ...process.env,
      PATH: `${fx.bin}:${process.env.PATH ?? ""}`,
      SCM_WORKTREES_DIR: fx.worktrees,
      AUTH_SECRET: "parent-auth-secret",
      DATABASE_URL: "postgres://parent-secret",
      FEISHU_APP_SECRET: "parent-feishu-secret",
      POSTGRES_PASSWORD: "parent-postgres-secret",
      AWS_SECRET_ACCESS_KEY: "parent-aws-secret",
      ...extraEnv,
    },
  }) as SpawnSyncReturns<string>;
}

describe("isolated development sessions", () => {
  it("writes a minimal 0600 environment without copying the main .env", () => {
    const fx = fixture();
    const result = run(fx, ["alpha", "--create-only"]);
    expect(result.status, result.stderr).toBe(0);
    const session = JSON.parse(result.stdout) as {
      destination: string;
      databaseUrl: string;
      storagePath: string;
      envPath: string;
    };
    const content = readFileSync(session.envPath, "utf8");
    expect(statSync(session.envPath).mode & 0o777).toBe(0o600);
    expect(content).toContain("# Generated by scripts/dev-session.ts");
    expect(content).toContain(`DATABASE_URL=${JSON.stringify(session.databaseUrl)}`);
    expect(content).toContain(`FILE_STORAGE_DIR=${JSON.stringify(session.storagePath)}`);
    expect(content).toMatch(/^AUTH_SECRET="[A-Za-z0-9_-]{40,}"$/m);
    expect(content).not.toContain("main-secret-must-not-copy");
    expect(content).not.toContain("FEISHU_APP_SECRET");
    expect(session.databaseUrl).toContain(session.destination);
    expect(session.storagePath).toContain(session.destination);
  });

  it("refuses to overwrite an unmarked worktree environment", () => {
    const fx = fixture();
    const first = run(fx, ["beta", "--create-only"]);
    expect(first.status, first.stderr).toBe(0);
    const session = JSON.parse(first.stdout) as { envPath: string };
    writeFileSync(session.envPath, "AUTH_SECRET=human-managed\n");
    const second = run(fx, ["beta", "--create-only"]);
    expect(second.status).not.toBe(0);
    expect(second.stderr).toContain("Refusing to reuse unmarked");
    expect(readFileSync(session.envPath, "utf8")).toBe("AUTH_SECRET=human-managed\n");
  });

  it("starts npm with generated session values and no inherited application secrets", () => {
    const fx = fixture();
    const captured = path.join(fx.root, "child.env");
    const fakeNpm = path.join(fx.bin, "npm");
    writeFileSync(fakeNpm, `#!/bin/sh\nenv | sort > ${JSON.stringify(captured)}\nexit 0\n`);
    chmodSync(fakeNpm, 0o755);
    const result = run(fx, ["gamma"]);
    expect(result.status, result.stderr).toBe(0);
    const childEnv = readFileSync(captured, "utf8");
    expect(childEnv).toContain("DATABASE_URL=pglite:");
    expect(childEnv).toContain("AUTH_URL=http://127.0.0.1:");
    expect(childEnv).toMatch(/^AUTH_SECRET=[A-Za-z0-9_-]{40,}$/m);
    expect(childEnv).toContain("FILE_STORAGE_DIR=");
    expect(childEnv).not.toContain("parent-auth-secret");
    expect(childEnv).not.toContain("parent-feishu-secret");
    expect(childEnv).not.toContain("parent-postgres-secret");
    expect(childEnv).not.toContain("parent-aws-secret");
    expect(childEnv).not.toContain("FEISHU_APP_SECRET=");
    expect(childEnv).not.toContain("POSTGRES_PASSWORD=");
    expect(childEnv).not.toContain("AWS_SECRET_ACCESS_KEY=");
  });
});
