/**
 * E7-02 指标语义注册表（唯一权威）。
 *
 * 问题：同一指标在不同页面各自解释（或根本不解释），口径写在横幅里、tooltip 里、注释里，
 * 改一处漏三处。本表让每个指标**定义一次**：公式、口径层级、单位、格式化、常见误解。
 * 页面引用 id 取说明，横幅与 tooltip 自动生成。
 *
 * 与 components/dictionary.ts 的分工：
 * - dictionary = **词**（术语、状态、动作、口径命名）；
 * - metrics    = **数**（指标的公式与解释）。
 */
import { TIER, type TierKey } from "@/components/dictionary";

export type MetricUnit = "qty" | "days" | "pct" | "count" | "money" | "ratio" | "minutes" | "hours";

export interface MetricDef {
  id: string;
  label: string;
  /** 一句话说明——用户能懂的话，不用行话 */
  short: string;
  /** 公式（给愿意深究的人） */
  formula?: string;
  unit: MetricUnit;
  tier: TierKey;
  /** 常见误解/边界——最容易被误读的地方 */
  caveat?: string;
}

export const METRICS: Record<string, MetricDef> = {
  activeSkuSpu: {
    id: "activeSkuSpu",
    label: "在用 SKU / SPU",
    short: "当前启用的可经营 SKU 数与产品 SPU 数",
    formula: "启用 SKU 数 / SPU 主数据总数",
    unit: "count",
    tier: "ledger",
    caveat: "主数据规模不是经营绩效；应结合动销与生命周期判断组合健康度",
  },
  salesQty: {
    id: "salesQty",
    label: "全渠道销量",
    short: "已导入销售事实在所选窗口内的数量合计",
    formula: "Σ销售月事实.qty",
    unit: "qty",
    tier: "snapshot",
    caveat: "当前只有月粒度数量；没有日销、收入、客户、区域和促销维度",
  },
  externalNetDemand: {
    id: "externalNetDemand",
    label: "外部净需求信号",
    short: "简道云最新成功批次中，天猫支付件数扣除成功退款件数后的观察需求",
    formula: "Σ支付件数 − Σ成功退款件数（销量、退款、SKU 对照各取最新成功批次）",
    unit: "qty",
    tier: "registry",
    caveat: "这是 observation-only 经营信号，未映射平台 SKU 不得归属系统 SKU；在身份覆盖、控制总量和 UAT 通过前，不得作为正式销量、补货或财务口径",
  },
  salesConcentration: {
    id: "salesConcentration",
    label: "销量集中度",
    short: "最新月累计贡献达到 80% 所需的品牌、渠道或 SKU 数",
    formula: "按销量降序累计，取累计占比首次达到 80% 的成员数",
    unit: "count",
    tier: "derived",
    caveat: "集中度只描述结构，不直接代表风险；还需结合替代性、渠道战略和利润判断",
  },
  onHandSystem: {
    id: "onHandSystem",
    label: "系统库存",
    short: "本系统所有仓的合计库存",
    formula: "Σ实时记账账 + 各快照仓最新快照",
    unit: "qty",
    tier: "ledger",
    caveat: "跨 SKU 相加时量纲混装（件/箱/kg），只作规模参考，不可当单一实物量",
  },
  onHandExternal: {
    id: "onHandExternal",
    label: "外部登记库存",
    short: "总库存明细文件口径（含海外/其他部门仓）",
    unit: "qty",
    tier: "registry",
    caveat: "系统未接管这些仓，数字来自文件、随文件时点老化——只作核对，绝不入账",
  },
  daysCover: {
    id: "daysCover",
    label: "可销天数",
    short: "按当前销速，现有库存还能卖多少天",
    formula: "系统库存 ÷ 近3月日均销（日均=近3月销量÷91）",
    unit: "days",
    tier: "derived",
    caveat: "无动销（日均=0）时无意义，显示为「无动销」而非 0 或 ∞",
  },
  coverFull: {
    id: "coverFull",
    label: "全管道可销天数",
    short: "算上在途与在制后还能卖多少天",
    formula: "（max(系统库存, 外部登记) + PO在途 + 在制 + 存量单 + 在订 − 借出未还） ÷ 日均销",
    unit: "days",
    tier: "derived",
    caveat: "含参考层数据，可信度低于系统口径；用于判断「是否真的缺」而非对账",
  },
  safetyQty: {
    id: "safetyQty",
    label: "安全库存",
    short: "为吸收需求与交期波动而应常备的量",
    formula: "z(服务水平) × √(交期 × 需求日标准差² + 日均² × 交期标准差²)",
    unit: "qty",
    tier: "derived",
    caveat: "样本<3个月或缺生产周期时降级为「兜底天数×日均」，界面会标注为兜底口径",
  },
  suggestQty: {
    id: "suggestQty",
    label: "建议补货量",
    short: "补到目标水位所需的量",
    formula: "逐日推演至首次跌破安全库存 → 补至（安全库存 + 目标覆盖天数需求）→ 施加 MOQ/订货倍数",
    unit: "qty",
    tier: "derived",
    caveat: "只在短缺落入生产周期内（来不及补）时才产生；生成的是草稿，仍走审批",
  },
  wape: {
    id: "wape",
    label: "预测误差 WAPE",
    short: "预测偏离实际的加权幅度，越小越准",
    formula: "Σ|预测−实际| ÷ Σ实际",
    unit: "ratio",
    tier: "derived",
    caveat: "比 MAPE 对零值稳健；电商稀疏序列应以此为准",
  },
  forecastBias: {
    id: "forecastBias",
    label: "预测偏差",
    short: "预测系统性偏高还是偏低",
    formula: "Σ(预测−实际) ÷ Σ实际",
    unit: "ratio",
    tier: "derived",
    caveat: "正=高估（备货偏多），负=低估（断货风险）；|偏差|≤10% 视为无系统性偏差",
  },
  turns: {
    id: "turns",
    label: "库存周转次数",
    short: "一年能把库存卖空几遍，越高越健康",
    formula: "窗口出库量 ÷ 平均库存 × (365 ÷ 窗口天数)",
    unit: "ratio",
    tier: "derived",
    caveat: "平均库存目前用当前在库近似（无每日库存历史），趋势可用、绝对值偏差需知悉",
  },
  dio: {
    id: "dio",
    label: "库存周转天数 DIO",
    short: "平均一件货在仓里待多久",
    formula: "365 ÷ 周转次数",
    unit: "days",
    tier: "derived",
  },
  adoptRate: {
    id: "adoptRate",
    label: "建议采纳率",
    short: "系统建议被批准进入执行的比例",
    formula: "（已审批+执行中+已完成的草稿）÷ 全部由建议生成的草稿",
    unit: "pct",
    tier: "derived",
    caveat: "采纳≠到货；要看货真落地请用「实际到货率」",
  },
  deliveredRate: {
    id: "deliveredRate",
    label: "实际到货率",
    short: "系统建议最终真有货入库的比例",
    formula: "下游 WO→JG→收货正常行实收>0 的草稿 ÷ 全部草稿",
    unit: "pct",
    tier: "ledger",
  },
  onTimeRate: {
    id: "onTimeRate",
    label: "供应商准时率",
    short: "供应商按承诺交期到货的比例",
    formula: "实际收货日 ≤ 承诺交期 的样本数 ÷ 有承诺交期的样本数",
    unit: "pct",
    tier: "derived",
    caveat: "实际收货以收货单建单时刻为准，仓库补录会使其偏晚",
  },
  expiryRiskQty: {
    id: "expiryRiskQty",
    label: "效期风险量（≤6月）",
    short: "剩余效期不超过 180 天的批次库存数量",
    formula: "Σ批次在库量，其中 过期日−口径日≤180天",
    unit: "qty",
    tier: "derived",
    caveat: "仅覆盖已维护批次与效期的库存；覆盖不足时不得外推到全部库存",
  },
  riskActionCount: {
    id: "riskActionCount",
    label: "风险处置 SKU",
    short: "风险库存工作台中需要负责人处理的 SKU 数",
    formula: "效期、货盘注记与销速规则命中的去重 SKU 数",
    unit: "count",
    tier: "derived",
    caveat: "命中表示需要判断，不代表系统已替人决定处置方式",
  },
  slowMoverCount: {
    id: "slowMoverCount",
    label: "滞销 SKU",
    short: "可销天数超过 180 天或当前无动销的 SKU 数",
    formula: "count(daysCover>180 或 日均销=0 且在库>0)",
    unit: "count",
    tier: "derived",
    caveat: "新品试销、季节品和停售品应按生命周期复核，不能只按阈值处置",
  },
  coverageSku: {
    id: "coverageSku",
    label: "库存覆盖 SKU",
    short: "系统库存与外部登记库存可进行同编码核对的 SKU 数",
    formula: "count(系统与外部登记均可映射的 SKU)",
    unit: "count",
    tier: "derived",
    caveat: "覆盖差异主要来自海外/其他部门仓与编码映射缺口，不能将未覆盖部分当作零",
  },
  finishedSkuCount: {
    id: "finishedSkuCount",
    label: "成品 SKU 数",
    short: "当前筛选范围内有库存或销售事实的在用成品 SKU 数",
    formula: "count(distinct SKU where skuType=finished and active=true)",
    unit: "count",
    tier: "ledger",
  },
  unknownOriginQty: {
    id: "unknownOriginQty",
    label: "来源不明库存",
    short: "当前在库超过可追溯历史入库流水的数量",
    formula: "max(当前在库−可追溯入库流水, 0)",
    unit: "qty",
    tier: "derived",
    caveat: "多为期初直接建账或无流水的快照仓；不能伪造入库日期，账龄按未知单列",
  },
  demandAchievement: {
    id: "demandAchievement",
    label: "需求达成率",
    short: "所选范围内销售达成量相对于登记需求量的比例",
    formula: "Σ销售达成 ÷ Σ登记需求",
    unit: "pct",
    tier: "derived",
    caveat: "当前来自月度登记文件，不是订单承诺或实时 sell-through；需求为 0 时显示数据不足",
  },
  qcPassRate: {
    id: "qcPassRate",
    label: "检验合格率",
    short: "已判定检验数量中正常合格的比例",
    formula: "正常合格数量 ÷（合格 + 返工 + 让步 + 报废）",
    unit: "pct",
    tier: "derived",
    caveat: "未检验与待判定数量不进入分母；必须同时查看待判定积压，避免幸存者偏差",
  },
  flowStageQty: {
    id: "flowStageQty",
    label: "全链阶段量级",
    short: "需求、计划、下单、到货与动销各阶段在当前窗口内的数量规模",
    unit: "qty",
    tier: "derived",
    caveat: "各阶段事实粒度和时间窗不同，只用于定位落差，不是严格转化或损耗率",
  },
  npdProgress: {
    id: "npdProgress",
    label: "新品组合进度",
    short: "进行中新品项目已完成的标准节点任务比例",
    formula: "Σ已完成节点 ÷ Σ已实例化节点",
    unit: "pct",
    tier: "ledger",
    caveat: "计划进度不等于商业成功；上市后销量、毛利、退货与复盘结论需单独接入",
  },
  wipPendingQty: {
    id: "wipPendingQty",
    label: "委外待收数量",
    short: "委外订单尚未通过正常收货行入库的剩余数量",
    formula: "Σ max(JG订单数量−正常行累计实收, 0)",
    unit: "qty",
    tier: "ledger",
    caveat: "跨 SKU 合计可能混合件、箱、kg 等基础单位，仅用于催交排序，不可视为统一产能",
  },
  platformIdentityCoverage: {
    id: "platformIdentityCoverage",
    label: "平台身份覆盖率",
    short: "平台唯一商品身份中已精确映射到系统 SKU 的比例",
    formula: "已精确映射的平台唯一身份 ÷ 平台唯一身份总数",
    unit: "pct",
    tier: "derived",
    caveat: "按平台自己的业务键分别计算，禁止跨平台直接去重或用名称模糊认领",
  },
  identityConflictCount: {
    id: "identityConflictCount",
    label: "身份冲突数",
    short: "同一来源作用域内指向多个条码或系统 SKU 的身份数量",
    formula: "count(distinct 来源scope + 类型 + 原始值 where 精确候选数 > 1)",
    unit: "count",
    tier: "registry",
    caveat: "冲突必须人工裁决；不能以销量、名称相似度或最近一次出现自动覆盖",
  },
  refundRate: {
    id: "refundRate",
    label: "成功退款率",
    short: "成功退款件数相对于支付件数的比例",
    formula: "Σ成功退款件数 ÷ Σ支付件数（同业务日、店铺与身份口径）",
    unit: "pct",
    tier: "derived",
    caveat: "退款申请、成功退款和退货入库不是同一事件；必须固定状态与观察窗口",
  },
  mappedDemandCoverage: {
    id: "mappedDemandCoverage",
    label: "已映射需求覆盖率",
    short: "可精确归属系统 SKU 的外部净需求占全部外部净需求的比例",
    formula: "已映射平台身份净需求 ÷ 全部平台身份净需求",
    unit: "pct",
    tier: "derived",
    caveat: "覆盖不足时不得把未映射需求当作零，也不得按名称摊给相似 SKU",
  },
  orderFulfillmentRate: {
    id: "orderFulfillmentRate",
    label: "订单履约率",
    short: "订单需求中已由有效出库事实履约的比例",
    formula: "有效出库数量 ÷ 有效订单数量（扣除取消并按退货口径单列）",
    unit: "pct",
    tier: "derived",
    caveat: "创建订单、平台发货和仓库出库时间不同，必须明确履约事件与截止日",
  },
  cashConversionDays: {
    id: "cashConversionDays",
    label: "订单到现金天数",
    short: "订单确认到对应回款或结算确认的平均业务天数",
    formula: "avg(回款/结算确认日 − 订单确认日)，仅含链路已对齐样本",
    unit: "days",
    tier: "derived",
    caveat: "未匹配订单不得从分母消失；应同时显示链路覆盖率和未收款尾部",
  },
  unreconciledOrderCount: {
    id: "unreconciledOrderCount",
    label: "未对账订单数",
    short: "无法完整连接订单、履约、退款与财务结算证据的订单数量",
    formula: "count(distinct 来源订单 where 任一必需链路缺失或金额超阈差异)",
    unit: "count",
    tier: "derived",
    caveat: "缺链路表示未知或待处理，不等同于漏单、坏账或平台错误",
  },
  inventoryReconciliationGap: {
    id: "inventoryReconciliationGap",
    label: "库存核对差异",
    short: "同一截止时点、仓库和 SKU 下各系统库存与 SCM 事实的差额",
    formula: "外部库存 − SCM 库存（按来源逐边显示，不互相抵销）",
    unit: "qty",
    tier: "derived",
    caveat: "跨 SKU 合计混合计量单位；缺仓、缺映射和不同截止日必须单列为未知",
  },
  openSupplyQty: {
    id: "openSupplyQty",
    label: "未结供给量",
    short: "已批准供应单据尚未由正常收货事实结清的数量",
    formula: "Σ max(批准数量 − 正常累计实收 − 已关闭数量, 0)",
    unit: "qty",
    tier: "ledger",
    caveat: "单据状态、单位和取消/红冲必须对齐；跨 SKU 合计只用于队列规模",
  },
  promiseReliability: {
    id: "promiseReliability",
    label: "承诺可信度",
    short: "有承诺日期的供应单行中按承诺数量和日期兑现的比例",
    formula: "按期足量完成的供应单行 ÷ 有有效承诺日的已到期供应单行",
    unit: "pct",
    tier: "derived",
    caveat: "未来未到期单行不进入分母；改期必须保留原承诺和变更审计",
  },
  netRevenue: {
    id: "netRevenue",
    label: "净回款/净收入",
    short: "销售支付金额扣除成功退款、折让与拒付后的净收入；平台费用另列，不混入收入定义",
    formula: "销售支付金额 − 成功退款 − 折让 − 拒付（平台费用另列）",
    unit: "money",
    tier: "derived",
    caveat: "当前简道云观察只实现支付金额减成功退款；折让、拒付、币种和关账未闭合时不得冒充会计净收入",
  },
  platformFeePaidAmount: {
    id: "platformFeePaidAmount",
    label: "平台费用支付金额",
    short: "简道云天猫费用项目汇总中，按币种分别累计的支付金额",
    formula: "Σ支付金额（负数按冲销/退回原样保留；按月份、店铺、费用项和币种分别汇总）",
    unit: "money",
    tier: "registry",
    caveat: "当前仅覆盖天猫渠道；财务确认正式费用字段、控制总量和关账期间前只能用于 UAT 与结构解释，且不得无依据分摊到 SKU",
  },
  channelContributionBeforeProductCost: {
    id: "channelContributionBeforeProductCost",
    label: "产品成本前渠道贡献",
    short: "净回款观察扣除可直接归属平台费用后的余额，尚未扣除商品成本",
    formula: "(支付金额 − 成功退款金额) − 平台费用支付金额",
    unit: "money",
    tier: "derived",
    caveat: "只在同一完整月份和店铺三源均有记录时计算；不含商品成本、折让、拒付和会计调整，绝不是毛利或利润",
  },
  contributionMarginRate: {
    id: "contributionMarginRate",
    label: "贡献毛利率",
    short: "净收入扣除商品成本和可变履约费用后保留的比例",
    formula: "(净收入 − 商品成本 − 可变履约费用) ÷ 净收入",
    unit: "pct",
    tier: "derived",
    caveat: "不能与会计毛利率混用；费用归属、期间和成本版本必须同时展示",
  },
  costCoverage: {
    id: "costCoverage",
    label: "成本覆盖率",
    short: "净收入样本中已取得同期间有效商品成本的比例",
    formula: "有有效成本的净收入 ÷ 全部净收入",
    unit: "pct",
    tier: "derived",
    caveat: "覆盖不足时不得把缺失成本当作零，毛利指标必须降级或留白",
  },
  supplierPriceVariance: {
    id: "supplierPriceVariance",
    label: "供应商价格偏差",
    short: "同 SKU 的供应商数量加权基础单位未税价相对窗口最低可比价的偏差",
    formula: "(供应商×SKU 数量加权基础单位未税价 − 同 SKU 窗口最低可比价) ÷ 同 SKU 窗口最低可比价",
    unit: "pct",
    tier: "derived",
    caveat: "PO 行币种、用友供应商身份、MOQ、账期和规格未验收前只作采购观察值；最低价不等于最优供应商，不可自动排名",
  },
  launchOnTimeRate: {
    id: "launchOnTimeRate",
    label: "新品按时上市率",
    short: "在承诺上市日前完成强制里程碑并产生有效首销的新品比例",
    formula: "按时完成且按时首销的新品项目 ÷ 到期新品项目",
    unit: "pct",
    tier: "derived",
    caveat: "移动计划日期不能抹除原承诺；延期原因和批准记录必须保留",
  },
  first90DayAchievement: {
    id: "first90DayAchievement",
    label: "首销 90 天达成率",
    short: "新品上市后 90 天实际净需求相对获批上市假设的比例",
    formula: "上市后 90 天累计净需求 ÷ 获批 90 天目标",
    unit: "pct",
    tier: "derived",
    caveat: "目标版本、正式上市日、退款和断货天数必须同时展示",
  },
  triangulationExceptionCount: {
    id: "triangulationExceptionCount",
    label: "三角核对异常数",
    short: "简道云观察、聚水潭履约和用友财务三边无法在阈值内解释的差异数量",
    formula: "count(distinct 业务日 + 身份 + 差异类型 where 差异超阈或链路缺失)",
    unit: "count",
    tier: "derived",
    caveat: "异常只是待解释证据，不能自动推断哪一边错误或自动调平",
  },
  exceptionSlaRate: {
    id: "exceptionSlaRate",
    label: "异常 SLA 达成率",
    short: "需要处理的跨系统异常中在目标时限内完成解释和关闭的比例",
    formula: "SLA 内关闭的异常 ÷ 已到期异常",
    unit: "pct",
    tier: "derived",
    caveat: "关闭必须有原因、责任人和证据；批量关闭不能算作有效解决",
  },
  cashGap13Week: {
    id: "cashGap13Week",
    label: "13 周现金缺口",
    short: "滚动 13 周情景中最低可用现金相对安全下限的不足金额",
    formula: "max(安全现金下限 − minₜ₌₁…₁₃(期初现金 + Σᵗ₍w₌₁₎(周流入_w − 周流出_w)), 0)",
    unit: "money",
    tier: "derived",
    caveat: "情景不是资金指令；未关账实际、税费、账期和融资边界必须明确",
  },
  scenarioCoverage: {
    id: "scenarioCoverage",
    label: "情景输入覆盖率",
    short: "S&OP 情景所需销量、供给、库存、成本和现金输入中已通过门禁的比例",
    formula: "已放行必需输入数 ÷ 必需输入总数",
    unit: "pct",
    tier: "derived",
    caveat: "覆盖不足时必须显示缺口，不得用零或乐观默认值补齐情景",
  },
  dataProductAdoptionRate: {
    id: "dataProductAdoptionRate",
    label: "真实建议采用率",
    short: "有明确业务决定的建议中，被采纳或修改后采纳的比例",
    formula: "（采纳 + 修改后采纳）÷（采纳 + 修改后采纳 + 拒绝）",
    unit: "pct",
    tier: "derived",
    caveat: "暂缓不进入分母；采用不等于结果正向，必须与真实结果和样本量一起看",
  },
  dataProductFalsePositiveRate: {
    id: "dataProductFalsePositiveRate",
    label: "真实误报率",
    short: "已经得到终局证据的建议中，被业务证据确认属于误报的比例",
    formula: "误报结果数 ÷ 非待观察结果数",
    unit: "pct",
    tier: "derived",
    caveat: "待观察样本不进入分母；结果纠正后只计算版本链叶子",
  },
  dataProductHandlingMinutes: {
    id: "dataProductHandlingMinutes",
    label: "平均处理时长",
    short: "已填写处理时长的当前有效结果记录的平均分钟数",
    formula: "Σ处理分钟 ÷ 有处理时长的有效结果数",
    unit: "minutes",
    tier: "derived",
    caveat: "缺失时保持空值，不按 0 分钟计入平均",
  },
  dataProductSavedHours: {
    id: "dataProductSavedHours",
    label: "实际节省工时",
    short: "有受控结果证据支持的实际节省工时合计",
    formula: "Σ当前有效结果.saved_hours",
    unit: "hours",
    tier: "derived",
    caveat: "只登记已发生、可核验的节省，不登记预测收益；缺失保持空值",
  },
  externalSkuRank: {
    id: "externalSkuRank",
    label: "SKU 外部销量排名",
    short: "按简道云天猫+拼多多近 30 天净件数对系统 SKU 排名，并列近 90 天与内部近 3 月销量",
    formula: "rank(Σ天猫支付件数 − 成功退款件数 + Σ拼多多有效订单件数，近 30 天，按系统 SKU；组合装按天猫组合表数量拆到组件)",
    unit: "qty",
    tier: "registry",
    caveat: "observation-only：只覆盖已映射到系统 SKU 的平台 SKU（覆盖率随表显示），未映射不按名称猜；不与内部 sales_monthly 相加、不驱动补货定量；组合装拆解为 D47 观察口径而非认领",
  },
  bondedOutboundDaily: {
    id: "bondedOutboundDaily",
    label: "保税仓日出库（观察）",
    short: "保税订单流按发货时间汇总的每日发货件数，可到 SKU × 批次 × 效期",
    formula: "Σ保税订单.发货数量（按发货日；剔除状态含「取消」的订单；跨 7 天滚动批次按源记录去重）",
    unit: "qty",
    tier: "registry",
    caveat: "保税仓是快照仓，本序列来自订单流不是仓库流水：不过账、不进销速、不能与快照在库相减推算期初；订单状态语义待业务确认",
  },
  expiryByBrand: {
    id: "expiryByBrand",
    label: "效期分布（按品牌）",
    short: "批次参考层里各品牌落在七个效期段位的批次数与数量",
    formula: "按 brands × 段位（已过期 / ≤3 月 / 3–6 月 / 6–12 月 / 12–18 月 / 18–24 月 / >24 月）聚合 batch_stocks.qty（qty>0 且有到期日）",
    unit: "qty",
    tier: "snapshot",
    caveat: "batch_stocks 是效期盘点载体不是账本；无品牌的 SKU 归「(未设品牌)」；跨 SKU 数量直加只作规模参考",
  },
  dataProductCashImpact: {
    id: "dataProductCashImpact",
    label: "实际现金影响",
    short: "有受控结果证据支持的实际现金改善或损失合计",
    formula: "Σ当前有效结果.cash_impact（CNY）",
    unit: "money",
    tier: "derived",
    caveat: "允许正负值；按采购、PMC、财务和管理员角色可见，缺失不按零处理",
  },
  /* ── 总监需求 W2-A（D51/D52/D53/D54）：库存日级/月级、估值、销售金额、占比 ── */
  onHandMonthEnd: {
    id: "onHandMonthEnd",
    label: "月末在库",
    short: "该月最后一天日终的全网在库数量；当月为当前时点",
    formula: "实时仓：当前余额 − Σ该月之后流水；快照仓：当月最后一期快照；两者相加",
    unit: "qty",
    tier: "ledger",
    caveat: "流水最早日之前的月份与当月无快照的快照仓留空，不补零；跨 SKU 按基础单位直加仅作规模参考（D52）",
  },
  dailyInOut: {
    id: "dailyInOut",
    label: "当日出入库",
    short: "当月至今每天的入库、出库与净变动",
    formula: "实时仓：按流水 Asia/Shanghai 日界分日汇总；快照仓：相邻快照差分（source=snapshot_delta）",
    unit: "qty",
    tier: "ledger",
    caveat: "快照仓差分落在后一快照日，跨多日时为累计值；缺日留空不补零；出库含调拨/发料/盘亏，非纯销售",
  },
  inventoryValue: {
    id: "inventoryValue",
    label: "库存金额",
    short: "在库数量按单位成本估值的金额（成本口径）",
    formula: "Σ在库数量 × 单位成本（sku_costs → 财务运营成本观察 → 无）",
    unit: "money",
    tier: "derived",
    caveat: "非财务账面；覆盖率低于门槛（默认 80%）时总额标「不完整」；历史月按当前成本版本估值；仅采购/PMC/财务/管理员可见（D51）",
  },
  inventoryValueCoverage: {
    id: "inventoryValueCoverage",
    label: "估值覆盖率",
    short: "有单位成本的在库数量占全部在库数量的比例",
    formula: "有成本 SKU 的在库数量 ÷ 全部在库数量 × 100",
    unit: "pct",
    tier: "derived",
    caveat: "按数量而非按 SKU 数；低于门槛时库存金额只能作参考，先补 sku_costs 或财务运营成本观察",
  },
  salesAmountMonthly: {
    id: "salesAmountMonthly",
    label: "当月销售金额",
    short: "财务口径的月度销售金额（手工录入，可用外部观察预填）",
    formula: "sales_amount_monthly 公司口径链尾；预填 = 天猫（支付 − 成功退款）+ 唯品会销售额 + 拼多多店铺成交额",
    unit: "money",
    tier: "registry",
    caveat: "含税/退款/平台费口径待财务追认（D53）；append-only 修正留痕；仅 PRICE_VISIBLE_ROLES（采购/计划/财务/管理员）可见，不进入任何补货计算",
  },
  inventorySalesRatio: {
    id: "inventorySalesRatio",
    label: "库存占比",
    short: "月末库存金额相对当月销售金额的比例，目标 45–47%",
    formula: "月末库存金额 ÷ 当月销售金额 × 100；并列（上月末 + 本月末）/ 2 ÷ 当月销售金额",
    unit: "pct",
    tier: "derived",
    caveat: "分子按成本、分母按售价，非同口径；缺任一侧不出数；基线 50%，目标带 inventory_sales_ratio_target_low/high（D54）",
  },
};

/* ── D58/D59 分层 / 权责 / 试点 / 周期主数据（2026-09-03 总监需求实施计划，W2 域 F） ── */
METRICS.skuTierShare = {
  id: "skuTierShare",
  label: "S/A/B/C 分层占比",
  short: "四档分层各有多少成品 SKU、各占近 6 月销量多少",
  formula: "按近 6 月销量件数降序累计，加入本项前累计占比 <S 切点→S，<A 切点→A，<B 切点→B，其余 C（切点 grade_s/a/b_pct，缺省 50/80/95）；占比 = 该档销量 ÷ 总销量",
  unit: "pct",
  tier: "derived",
  caveat: "按件数不按金额（unit_cost 覆盖率不足）；月度固化到 sku_planning_policy，人工覆写只改生效分层不改规则分层；零销量恒 C",
};
METRICS.ownershipMix = {
  id: "ownershipMix",
  label: "备货权责分布",
  short: "供应链直出 / 联合评审 / 运营按需 各有多少 SKU",
  formula: "S/A/B ∧ XYZ=X ∧ 无异动 ∧ 周期已知 → 供应链直出；S/A/B 其余 → 联合评审；C → 运营按需",
  unit: "count",
  tier: "derived",
  caveat: "XYZ 样本 <6 月或无动销记「样本不足」而非 X，会落入联合评审；周期主数据缺失同样阻塞直出——名单短往往是主数据问题不是需求问题",
};
METRICS.pilotEligible = {
  id: "pilotEligible",
  label: "试点候选",
  short: "满足「稳定品」四条件、可先纳入补货试点的 SKU 数与销量占比",
  formula: "候选 = 生效分层 S/A/B ∧ XYZ=X ∧ 加工/在途周期已维护 ∧ 无异动命中；占比 = 候选近 6 月销量 ÷ 全部成品近 6 月销量",
  unit: "count",
  tier: "derived",
  caveat: "候选 ≠ 已纳入（pilot 标记由生产计划人工点选）；成功指标与评估周期待业务确定，本指标不代表试点成效",
};
METRICS.leadTimeCoverage = {
  id: "leadTimeCoverage",
  label: "周期主数据完整度",
  short: "各分层成品中加工周期与在途周期都已维护的比例",
  formula: "完整 = sku_params.normal_lead_days>0 ∧ logistics_lead_days 非空；按最近固化期分层分桶；S/A/B 缺任一即阻塞",
  unit: "pct",
  tier: "ledger",
  caveat: "缺失时预警阈值回落 default_production/logistics_lead_days（D57），核心品的阈值建立在假设上；未固化分层的 SKU 归「未分层」桶，不假装分层",
  todoOpen: {
    id: "todoOpen",
    label: "未完成待办",
    short: "当前处于「待处理 / 进行中」的待办条数",
    formula: "count(work_items.status ∈ {open, in_progress})",
    unit: "count",
    tier: "ledger",
    caveat: "含手工来源；按人看「指派给我」，按角色看 owner_role；不是工作量，只是待跟进数",
  },
  todoOverdue: {
    id: "todoOverdue",
    label: "逾期待办",
    short: "未完成且已过截止日的待办条数",
    formula: "count(status ∈ {open, in_progress} ∧ due_date < 今天(Asia/Shanghai))",
    unit: "count",
    tier: "ledger",
    caveat: "无截止日的待办不会逾期；完成晚于截止日在完成率口径里记「完成不按时」，不再算逾期",
  },
  todoCompletionRate: {
    id: "todoCompletionRate",
    label: "待办完成率",
    short: "系统触发（告警/复核）待办的完成占比，按创建月统计，只读不打分",
    formula: "已完成 ÷ (总数 − 已取消)；按时率 = 按时完成 ÷ 已完成",
    unit: "pct",
    tier: "derived",
    caveat: "手工来源不计入；创建后不足 10 分钟即关闭的标「可疑」仅提示；D61：绩效 = 证据导出，不评分",
  },
  goalAttainment: {
    id: "goalAttainment",
    label: "目标达成度",
    short: "部门目标的实际值相对目标值的达成百分比",
    formula: "越高越好：实际 ÷ 目标 × 100；越低越好：目标 ÷ 实际 × 100",
    unit: "pct",
    tier: "derived",
    caveat: "auto 实际值取自已登记读模型缓存，取不到留空不编造；手工值必附证据；部门 = 角色（D61）",
  /* ── D65 数据质量（W2-H） ── */
  dataAccuracyRpa: {
    id: "dataAccuracyRpa",
    label: "RPA 仓库准确率",
    short: "RPA/电商部库存快照与聚水潭对账在 SKU 日级的一致率",
    formula: "近 30 天 recon_diffs 中 |系统数量 − 聚水潭数量| ≤ 容差(dq_tolerance_pct)% 的行数 ÷ 总行数",
    unit: "pct",
    tier: "derived",
    caveat: "目标 95%；并列的盘点命中率把未改动行计为命中、偏高；快照跳变只警告不阻断",
  },
  dataAccuracyManual: {
    id: "dataAccuracyManual",
    label: "人工单据链准确率",
    short: "人工上传模板的首次通过率，作为人工录入「首次正确率」的代理",
    formula: "近 30 天该类模板 staging 成功行 ÷（成功行 + 拒收行）",
    unit: "pct",
    tier: "derived",
    caveat: "目标 90%；只是代理口径，单据链本身的纠错靠红字冲销留痕，不在此统计",
  },
  snapshotJumpAlerts: {
    id: "snapshotJumpAlerts",
    label: "快照跳变告警",
    short: "快照仓最近两批相邻快照出现总量跳变、SKU 大量消失或负数量的仓库数",
    formula: "|ΣQty 变动| > 30% 或 消失 SKU 占比 > 10% 或 存在负数量 的快照仓计数",
    unit: "count",
    tier: "derived",
    caveat: "阈值可调（dq_snapshot_qty_jump_pct / dq_snapshot_vanished_pct）；无上一批的仓只出行数不告警",
  },
  salesConsistencyPct: {
    id: "salesConsistencyPct",
    label: "销量口径一致率",
    short: "内部 sales_monthly 与天猫日销观察（支付 − 退款）按 SKU × 完整月的一致比例",
    formula: "一致行 ÷（一致行 + 例外行）；一致 = |内部 − 外部| ≤ max(绝对下限, max(内部,外部) × 相对容差)；两侧均低于量下限的行不进分母",
    unit: "pct",
    tier: "registry",
    caveat: "只比较两侧都有记录的完整月，单侧缺失记为未覆盖不补 0；一致率不裁定谁对谁错；观察数据不进过账",
  },
  dqReviewsPending: {
    id: "dqReviewsPending",
    label: "待核对项",
    short: "数据质量周/月核对包中尚未完成或豁免的记录数",
    formula: "data_quality_reviews.status = pending 的行数",
    unit: "count",
    tier: "ledger",
    caveat: "连续 4 周完成且达标后转为月核对；豁免必须填原因且不算达标",
  /* ── W2-G 采购订单指标 / 降本 / 供应商账期（D63、D64） ── */
  poOrderedQty: {
    id: "poOrderedQty",
    label: "已下单数量",
    short: "期间内审批通过的采购订单行数量合计（基础单位）",
    formula: "Σ已批 PO 行 qty × uomFactor，按审批通过日归期",
    unit: "qty",
    tier: "ledger",
    caveat: "已下单 = PO 审批通过时点，不是制单；草稿/待审/驳回/作废不计；采购退货不回冲已下单量",
  },
  poOrderedAmount: {
    id: "poOrderedAmount",
    label: "已下单金额",
    short: "期间内审批通过的采购订单未税金额（含税并列）",
    formula: "Σ已批 PO 行 price × qty 去税（含税价 ÷ (1+税率)）；含税额并列",
    unit: "money",
    tier: "ledger",
    caveat: "采购订单口径，不是应付或已付；仅采购/PMC/财务/管理员可见金额",
  },
  poOrderToDeliveryDays: {
    id: "poOrderToDeliveryDays",
    label: "订单至交付",
    short: "PO 审批通过到首批收货的天数分布（P50/P90），全收并列",
    formula: "首批 = 首张生效 SH 建单日 − 审批通过日；全收 = 累计已收 ≥ 应收时的最后一张 SH",
    unit: "days",
    tier: "derived",
    caveat: "样本 < 3 不出 P50/P90（标样本不足）；与交期学习页的「制单 → 收货」口径不同",
  },
  costSavingYtd: {
    id: "costSavingYtd",
    label: "降本额（YTD）",
    short: "当年已批采购行相对上一年度基线价的降价节省合计，只计降价",
    formula: "Σ max(0, 基线单价 − 当前单价) × 当年已批数量；基线 = 上一年度已批数量加权未税均价（无则首个）",
    unit: "money",
    tier: "derived",
    caveat: "涨价另列为增支，不与降本轧差；基线按 SKU 跨供应商；无可比基线的行计入「不可比」",
  },
  supplierOtif: {
    id: "supplierOtif",
    label: "供应商 OTIF",
    short: "承诺交期窗口内足量收齐的 PO 占可评 PO 的比例",
    formula: "准时 = 全收完成日 ≤ 承诺日 + otif_window_days；足量 = 累计已收 ≥ 应收 × (1 − 容差)；OTIF = 命中 ÷ 可评",
    unit: "pct",
    tier: "derived",
    caveat: "缺承诺交期进「不可评」，未到期未收齐进「待评」，两者都不进分母；承诺日 = 行交期优先、表头兜底",
  },
  paymentTermAttainment: {
    id: "paymentTermAttainment",
    label: "账期达成率",
    short: "账期谈判候选供应商中，已登记月结且天数达到目标下限的比例",
    formula: "候选中达标数 ÷ 候选数；候选 = 合作 ≥ payment_term_min_years 且当年池内排名较上年上升",
    unit: "pct",
    tier: "derived",
    caveat: "合作起始日由最早已批 PO/JG 系统推算；候选为 0 时无值而非 100%",
  },
  creditTermSpendShare: {
    id: "creditTermSpendShare",
    label: "账期类采购额占比",
    short: "月结类供应商当年采购额占全部当年采购额的比例",
    formula: "Σ月结供应商（PO 未税额 + JS 结算额）÷ Σ全部供应商同口径采购额",
    unit: "pct",
    tier: "derived",
    caveat: "代理指标：按采购订单/结算口径，不是应付余额占比；真应付待用友授权",
  /* ── D60 调拨线路 / 各仓周转（W2-C 登记） ── */
  transferLaneAvgFee: {
    id: "transferLaneAvgFee",
    label: "线路均价（元/件）",
    short: "同一调拨线路近 180 天已完成单据的数量加权单位费用，作为成本基线",
    formula: "Σ线路费用净额 ÷ Σ线路件数（窗口 transfer_cost_window_days，仅登记过费用的单）",
    unit: "money",
    tier: "ledger",
    caveat: "线路 = (转出仓, 转入仓, 调拨类型)；不跨线路轧差、不进库存成本；费用从上线起累计，样本不足时只提醒不告警；仅采购/PMC/财务/管理员可见",
  },
  transferLaneSamples: {
    id: "transferLaneSamples",
    label: "线路样本数",
    short: "线路基线里登记过费用的已完成调拨单数",
    formula: "count(同线路窗口内 有费用登记 的已完成单)",
    unit: "count",
    tier: "ledger",
    caveat: "样本 < 8 时偏差判定最多为提醒并标「样本不足」，≥ 8 才走中位数+MAD 统计判定；未登记费用 ≠ 零费用",
  },
  warehouseTurns: {
    id: "warehouseTurns",
    label: "逐仓周转次数",
    short: "某个实时仓在窗口内把平均在库卖空几遍（年化）",
    formula: "窗口出库 ÷ ((期初+期末)/2) × (365 ÷ 窗口天数)，期初由流水倒推",
    unit: "ratio",
    tier: "derived",
    caveat: "出库含调拨/发料/盘亏等非纯销售出库；快照仓无流水不计算；跨 SKU 数量直加仅作规模参考；总周转只汇总实时仓",
  },
  warehouseDio: {
    id: "warehouseDio",
    label: "逐仓库存天数",
    short: "某个实时仓平均一件货在仓里待多久",
    formula: "365 ÷ 逐仓周转次数",
    unit: "days",
    tier: "derived",
    caveat: "窗口内零出库时为空（不用假数字表达「永远卖不完」）；快照仓不计算",
  },
};

/** 取指标定义；未登记返回 undefined（调用方应回退到原文案） */
export function metric(id: string): MetricDef | undefined {
  return METRICS[id];
}

/** 生成 tooltip 文案：一句话 + 公式 + 口径层级 + 注意事项 */
export function metricTooltip(id: string): string {
  const m = METRICS[id];
  if (!m) return "";
  const lines = [m.short];
  if (m.formula) lines.push(`公式：${m.formula}`);
  lines.push(`口径：${TIER[m.tier].full}`);
  if (m.caveat) lines.push(`注意：${m.caveat}`);
  return lines.join("\n");
}
