import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { spawn, spawnSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import path from "node:path";

const SESSION_ENV_MARKER = "# Generated by scripts/dev-session.ts; session-local values only.";
const SAFE_INHERITED_ENV = [
  "PATH",
  "HOME",
  "USER",
  "LOGNAME",
  "SHELL",
  "TMPDIR",
  "TMP",
  "TEMP",
  "LANG",
  "LC_ALL",
  "LC_CTYPE",
  "TERM",
  "COLORTERM",
  "FORCE_COLOR",
  "NO_COLOR",
] as const;
type EnvMap = Record<string, string | undefined>;

function git(args: string[], cwd = process.cwd()): string {
  const result = spawnSync("git", args, { cwd, encoding: "utf8" });
  if (result.status !== 0) {
    throw new Error(result.stderr.trim() || `git ${args.join(" ")} failed`);
  }
  return result.stdout.trim();
}

function safeName(value: string | undefined): string {
  const name = value?.trim().toLowerCase();
  if (!name || !/^[a-z0-9][a-z0-9-]{1,40}$/.test(name)) {
    throw new Error("Usage: npm run dev:session -- <name> [--create-only]");
  }
  return name;
}

function basePort(name: string): number {
  let hash = 0;
  for (const char of name) hash = (hash * 31 + char.charCodeAt(0)) >>> 0;
  return 3100 + (hash % 200);
}

function portAvailable(port: number): boolean {
  const result = spawnSync("lsof", ["-nP", `-iTCP:${port}`, "-sTCP:LISTEN"], {
    stdio: "ignore",
  });
  if (result.status === 0) return false;
  if (result.status === 1) return true;
  throw new Error("Unable to inspect local ports with lsof");
}

function generatedSecret(envPath: string): string {
  if (!existsSync(envPath)) return randomBytes(32).toString("base64url");

  const stat = lstatSync(envPath);
  if (!stat.isFile() || stat.isSymbolicLink()) {
    throw new Error(`Refusing non-regular session environment file: ${envPath}`);
  }
  const content = readFileSync(envPath, "utf8");
  if (!content.startsWith(`${SESSION_ENV_MARKER}\n`)) {
    throw new Error(
      `Refusing to reuse unmarked ${envPath}; review and remove it before recreating this isolated session`,
    );
  }
  const match = content.match(/^AUTH_SECRET=(.+)$/m);
  if (!match) throw new Error(`Generated session environment is missing AUTH_SECRET: ${envPath}`);
  let secret: unknown;
  try {
    secret = JSON.parse(match[1]);
  } catch {
    throw new Error(`Generated session environment has an invalid AUTH_SECRET: ${envPath}`);
  }
  if (typeof secret !== "string" || secret.length < 32) {
    throw new Error(`Generated session environment has a weak AUTH_SECRET: ${envPath}`);
  }
  return secret;
}

function writeSessionEnv(
  envPath: string,
  values: Record<"DATABASE_URL" | "AUTH_SECRET" | "AUTH_URL" | "FILE_STORAGE_DIR", string>,
): void {
  const content = [
    SESSION_ENV_MARKER,
    `DATABASE_URL=${JSON.stringify(values.DATABASE_URL)}`,
    `AUTH_SECRET=${JSON.stringify(values.AUTH_SECRET)}`,
    `AUTH_URL=${JSON.stringify(values.AUTH_URL)}`,
    `FILE_STORAGE_DIR=${JSON.stringify(values.FILE_STORAGE_DIR)}`,
    'SCM_RUN_JOBS="0"',
    "",
  ].join("\n");
  writeFileSync(envPath, content, {
    encoding: "utf8",
    flag: existsSync(envPath) ? "w" : "wx",
    mode: 0o600,
  });
  chmodSync(envPath, 0o600);
}

function sanitizedChildEnv(explicit: EnvMap): NodeJS.ProcessEnv {
  const env: EnvMap = {};
  for (const key of SAFE_INHERITED_ENV) {
    const value = process.env[key];
    if (value !== undefined) env[key] = value;
  }
  return { ...env, ...explicit } as NodeJS.ProcessEnv;
}

async function main(): Promise<void> {
  const name = safeName(process.argv[2]);
  const createOnly = process.argv.includes("--create-only");
  const repoRoot = git(["rev-parse", "--show-toplevel"]);
  const commonGitDir = realpathSync(git(["rev-parse", "--git-common-dir"]));
  const mainRoot = path.dirname(commonGitDir);
  const worktreesRoot =
    process.env.SCM_WORKTREES_DIR?.trim() ||
    path.join(path.dirname(mainRoot), "worktrees");
  const destination = path.join(worktreesRoot, name);
  const branch = `codex/${name}`;
  mkdirSync(worktreesRoot, { recursive: true });

  if (!existsSync(destination)) {
    const branchExists = spawnSync(
      "git",
      ["show-ref", "--verify", "--quiet", `refs/heads/${branch}`],
      { cwd: repoRoot },
    ).status === 0;
    git(
      branchExists
        ? ["worktree", "add", destination, branch]
        : ["worktree", "add", "-b", branch, destination, "HEAD"],
      repoRoot,
    );
  }

  const sourceModules = path.join(mainRoot, "node_modules");
  const targetModules = path.join(destination, "node_modules");
  if (!existsSync(targetModules) && existsSync(sourceModules)) {
    symlinkSync(sourceModules, targetModules, "dir");
  }

  let port = basePort(name);
  while (!portAvailable(port) && port < 3300) port += 1;
  if (port >= 3300 && !portAvailable(port)) {
    throw new Error("No available development port between 3100 and 3300");
  }
  const sessionDataPath = path.join(destination, ".data", "session");
  const databasePath = path.join(sessionDataPath, "db");
  const storagePath = path.join(sessionDataPath, "storage");
  mkdirSync(sessionDataPath, { recursive: true, mode: 0o700 });
  chmodSync(sessionDataPath, 0o700);

  const targetEnv = path.join(destination, ".env");
  const authUrl = `http://127.0.0.1:${port}`;
  const authSecret = generatedSecret(targetEnv);
  const databaseUrl = `pglite:${databasePath}`;
  writeSessionEnv(targetEnv, {
    DATABASE_URL: databaseUrl,
    AUTH_SECRET: authSecret,
    AUTH_URL: authUrl,
    FILE_STORAGE_DIR: storagePath,
  });

  const session = {
    name,
    branch,
    destination,
    port,
    databaseUrl,
    storagePath,
    envPath: targetEnv,
  };
  console.log(JSON.stringify(session, null, 2));
  if (createOnly) return;

  const child = spawn("npm", ["run", "dev"], {
    cwd: destination,
    stdio: "inherit",
    env: sanitizedChildEnv({
      PORT: String(port),
      AUTH_URL: authUrl,
      AUTH_SECRET: authSecret,
      DATABASE_URL: databaseUrl,
      FILE_STORAGE_DIR: storagePath,
      SCM_RUN_JOBS: "0",
      TZ: "Asia/Shanghai",
    }),
  });
  child.on("exit", (code) => process.exit(code ?? 0));
}

void main();
